### ISSUE TITLE
e_parseTest::testToForm()

### ISSUE THREAD

**Issue by SimSync** [e107inc/e107-test#11]
@CaMer0n In the mentioned test, you are comparing $db to $actual, but shouldn't it be $orig to $actual?
Or am i getting something wrong?

```
                public function testToForm()
		{
			$orig = "lr.src = window._lr.url + '/Scripts/api.js';";
			$db = $this->tp->toDB($orig);
			$actual = $this->tp->toForm($db);
			$this->assertEquals($db,$actual);		
		}
```
And even if that would be correct, why should i use toForm() if the result is the same as without...?

**Comment by CaMer0n** [comment]
@SimSync You're right, that's a typo.
